config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'barbers#index'

  get('/works_ats/new', { :controller => 'works_ats', :action => 'new' })
  get('/create_works_at', { :controller => 'works_ats', :action => 'create' })

  get('/works_ats', { :controller => 'works_ats', :action => 'index' })
  get('/works_ats/:id', { :controller => 'works_ats', :action => 'show' })

  get('/works_ats/:id/edit', { :controller => 'works_ats', :action => 'edit' })
  get('/update_works_at/:id', { :controller => 'works_ats', :action => 'update' })

  get('/delete_works_at/:id', { :controller => 'works_ats', :action => 'destroy' })

  get('/ratings/new', { :controller => 'ratings', :action => 'new' })
  get('/create_rating', { :controller => 'ratings', :action => 'create' })

  get('/ratings', { :controller => 'ratings', :action => 'index' })
  get('/ratings/:id', { :controller => 'ratings', :action => 'show' })

  get('/ratings/:id/edit', { :controller => 'ratings', :action => 'edit' })
  get('/update_rating/:id', { :controller => 'ratings', :action => 'update' })

  get('/delete_rating/:id', { :controller => 'ratings', :action => 'destroy' })

  get('/favorites/new', { :controller => 'favorites', :action => 'new' })
  get('/create_favorite', { :controller => 'favorites', :action => 'create' })

  get('/favorites', { :controller => 'favorites', :action => 'index' })
  get('/favorites/:id', { :controller => 'favorites', :action => 'show' })

  get('/favorites/:id/edit', { :controller => 'favorites', :action => 'edit' })
  get('/update_favorite/:id', { :controller => 'favorites', :action => 'update' })

  get('/delete_favorite/:id', { :controller => 'favorites', :action => 'destroy' })

  get('/hoods/new', { :controller => 'hoods', :action => 'new' })
  get('/create_hood', { :controller => 'hoods', :action => 'create' })

  get('/hoods', { :controller => 'hoods', :action => 'index' })
  get('/hoods/:id', { :controller => 'hoods', :action => 'show' })

  get('/hoods/:id/edit', { :controller => 'hoods', :action => 'edit' })
  get('/update_hood/:id', { :controller => 'hoods', :action => 'update' })

  get('/delete_hood/:id', { :controller => 'hoods', :action => 'destroy' })

  get('/users/new', { :controller => 'users', :action => 'new' })
  get('/create_user', { :controller => 'users', :action => 'create' })

  get('/users', { :controller => 'users', :action => 'index' })
  get('/users/:id', { :controller => 'users', :action => 'show' })

  get('/users/:id/edit', { :controller => 'users', :action => 'edit' })
  get('/update_user/:id', { :controller => 'users', :action => 'update' })

  get('/delete_user/:id', { :controller => 'users', :action => 'destroy' })

  get('/barbershops/new', { :controller => 'barbershops', :action => 'new' })
  get('/create_barbershop', { :controller => 'barbershops', :action => 'create' })

  get('/barbershops', { :controller => 'barbershops', :action => 'index' })
  get('/barbershops/:id', { :controller => 'barbershops', :action => 'show' })

  get('/barbershops/:id/edit', { :controller => 'barbershops', :action => 'edit' })
  get('/update_barbershop/:id', { :controller => 'barbershops', :action => 'update' })

  get('/delete_barbershop/:id', { :controller => 'barbershops', :action => 'destroy' })

  get('/barbers/new', { :controller => 'barbers', :action => 'new' })
  get('/create_barber', { :controller => 'barbers', :action => 'create' })

  get('/barbers', { :controller => 'barbers', :action => 'index' })
  get('/barbers/:id', { :controller => 'barbers', :action => 'show' })

  get('/barbers/:id/edit', { :controller => 'barbers', :action => 'edit' })
  get('/update_barber/:id', { :controller => 'barbers', :action => 'update' })

  get('/delete_barber/:id', { :controller => 'barbers', :action => 'destroy' })

end

app/models/barbershop.rb
class Barbershop < ActiveRecord::Base
  validates(:name, { :presence => true })
  validates(:address, { :uniqueness => true, :presence => true })
  validates(:hood_id, { :presence => true })
  validates(:telephone, { :presence => true })

  has_many :works_ats
  has_many :barbers, :through => :works_ats
  belongs_to :hood

end

app/controllers/barbershops_controller.rb
require 'open-uri'
require 'json'

class BarbershopsController < ApplicationController
  def index
    @barbershops = Barbershop.all
  end

  def show
    @barbershop = Barbershop.find(params[:id])
  end

  def new
    @barbershop = Barbershop.new
  end

  def create
    @barbershop = Barbershop.new
    @barbershop.name = params[:name]
    @barbershop.address = params[:address]
    @barbershop.hood_id = params[:hood_id]
    @barbershop.telephone = params[:telephone]
    @url_safe_address = URI.encode(@barbershop.address)
    @url_of_data = "http://maps.googleapis.com/maps/api/geocode/json?address=#{@url_safe_address}"
    @raw_data = open(@url_of_data).read
    @parsed_data = JSON.parse(@raw_data)
    @latitude = @parsed_data["results"][0]["geometry"]["location"]["lat"]
    @longitude = @parsed_data["results"][0]["geometry"]["location"]["lng"]
    @barbershop.latitude = @latitude
    @barbershop.longitude = @longitude

    if @barbershop.save
      redirect_to "/barbershops", :notice => "Barbershop created successfully."
    else
      render 'new'
    end
  end

  def edit
    @barbershop = Barbershop.find(params[:id])
  end

  def update
    @barbershop = Barbershop.find(params[:id])

    @barbershop.name = params[:name]
    @barbershop.address = params[:address]
    @barbershop.hood_id = params[:hood_id]
    @barbershop.telephone = params[:telephone]
    @url_safe_address = URI.encode(@barbershop.address)
    @url_of_data = "http://maps.googleapis.com/maps/api/geocode/json?address=#{@url_safe_address}"
    @raw_data = open(@url_of_data).read
    @parsed_data = JSON.parse(@raw_data)
    @latitude = @parsed_data["results"][0]["geometry"]["location"]["lat"]
    @longitude = @parsed_data["results"][0]["geometry"]["location"]["lng"]
    @barbershop.latitude = @latitude
    @barbershop.longitude = @longitude

    if @barbershop.save
      redirect_to "/barbershops", :notice => "Barbershop updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @barbershop = Barbershop.find(params[:id])

    @barbershop.destroy

    redirect_to "/barbershops", :notice => "Barbershop deleted."
  end
end

app/views/barbershops/edit.html.erb
<div class="content-container">
<!-- Validation failure messages -->

<% if @barbershop.errors.any? %>
  <% @barbershop.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Simple full-width example -->

<div class="page-header">
  <h1>Edit <%= @barbershop.name %></h1>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/update_barbershop/<%= @barbershop.id %>" class="form-horizontal">
      <!-- Label and input for name -->
      <div class="form-group">
        <label for="name" class="col-sm-2 control-label">
          Name
        </label>
        <div class="col-sm-10">
          <input type="text" id="name" name="name" placeholder="Name" class="form-control" value="<%= @barbershop.name %>">
        </div>
      </div>

      <!-- Label and input for address -->
      <div class="form-group">
        <label for="address" class="col-sm-2 control-label">
          Address
        </label>
        <div class="col-sm-10">
          <input type="text" id="address" name="address" placeholder="Address" class="form-control" value="<%= @barbershop.address %>">
        </div>
      </div>

      <!-- Label and input for hood_id -->
      <div class="form-group">
        <label for="hood_id" class="col-sm-2 control-label">
          Hood
        </label>
        <div class="col-sm-10">
          <!-- <input type="text" id="hood_id" name="hood_id" placeholder="Hood" class="form-control" value="<%= @barbershop.hood_id %>"> -->
          <%= select_tag(:hood_id, options_from_collection_for_select(Hood.all, :id, :name), :class => "form-control" ) %>
        </div>
      </div>

      <!-- Label and input for telephone -->
      <div class="form-group">
        <label for="telephone" class="col-sm-2 control-label">
          Telephone
        </label>
        <div class="col-sm-10">
          <input type="text" id="telephone" name="telephone" placeholder="Telephone" class="form-control" value="<%= @barbershop.telephone %>">
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <input type="submit" value="Update Barbershop" class="btn btn-warning">
          or
          <a href="/barbershops/<%= @barbershop.id %>">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</div>

app/views/barbershops/index.html.erb
<div class="content-container">
<div class="page-header">
  <h1>
    Barbershops
<% if current_user.admin == true %>
    <a href="/barbershops/new" class="btn btn-lg btn-success"><i class="fa fa-plus"></i></a>
    <% end %>
  </h1>
</div>

<div class = "one-half-left">
<!-- Put cordinates into an array -->
<% @barbershop_coords = [] %>
<% @barbershops.each do |marker| %>
<%  @barbershop_coords.push(['test', marker.latitude , marker.longitude]) %>
<% end %>

<!-- Code for Google Map -->

<div id="map-canvas" style="height: 400px"></div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<script>



  function initialize() {

    var map;
    var myCenter = new google.maps.LatLng(41.8750579, -87.6248076);

    var mapOptions = {
      zoom: 15,
      center: myCenter
    };

            // Display a map on the page
            map = new google.maps.Map(document.getElementById('map-canvas'),
              mapOptions);


            //Multiple Makers

        <% @barbershops.each do |barbershop| %>

            var myLatlng = new google.maps.LatLng(<%= barbershop.latitude %>, <%= barbershop.longitude %>);
            var marker = new google.maps.Marker({
              position: myLatlng,
              map: map,
              title: '<%= barbershop.name %>'

            });
       <% end %>

          }

          google.maps.event.addDomListener(window, 'load', initialize);

        </script>


</div>

</div>
<!-- Simple table layout example -->
<div class="content-container">
<div class ="one-half-right"
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Address</th>
          <th>Neighborhood</th>
          <th>Telephone</th>
<!--           <th>Lat</th>
          <th>Long</th> -->
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @barbershops.each do |barbershop| %>
        <tr>
          <td><a href="/barbershops/<%= barbershop.id %>"><%= barbershop.name %></a></td>
          <td><%= barbershop.address %></td>
          <td><a href="/hoods/<%= barbershop.hood.id %>"><%= barbershop.hood.name %></a></td>
          <td><%= barbershop.telephone %></td>
          <td><%#= barbershop.latitude %></td>
          <td><%#= barbershop.longitude %></td>
         <!--  <td>
            <a href="/barbershops/<%= barbershop.id %>" class="btn btn-primary">
              <i class="fa fa-search-plus"></i>
            </a>
          </td> -->
          <% if current_user.admin == true %>
          <td>
            <a href="/barbershops/<%= barbershop.id %>/edit" class="btn btn-warning">
              <i class="fa fa-edit"></i>
            </a>
          </td>
          <td>
            <a href="/delete_barbershop/<%= barbershop.id %>" class="btn btn-danger">
              <i class="fa fa-trash-o"></i>
            </a>
          </td>
          <% end %>
          <dd>
          </dd>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>
</div>
</div>

<!-- End simple table layout example -->


<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container').isotope({
      itemSelector: '.isotope-item',
      layoutMode: 'masonry',
      filter: function() {
        return qsRegex ? $(this).text().match( qsRegex ) : true;
      }
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

</div>

<!-- End responsive, Isotope-based layout example -->

app/views/barbershops/new.html.erb
<div class="content-container">
<!-- Validation failure messages -->

<% if @barbershop.errors.any? %>
  <% @barbershop.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Simple full-width example-->

<div class="page-header">
  <h1>Add Barbershop</h1>
</div>

<div class="row">
  <div class="col-md-12">
    <form action="/create_barbershop" class="form-horizontal">
      <!-- Label and input for name -->
      <div class="form-group">
        <label for="name" class="col-sm-2 control-label">
          Name
        </label>
        <div class="col-sm-10">
          <input type="text" id="name" name="name" placeholder="Name" class="form-control" value="<%= @barbershop.name %>">
        </div>
      </div>

      <!-- Label and input for address -->
      <div class="form-group">
        <label for="address" class="col-sm-2 control-label">
          Address
        </label>
        <div class="col-sm-10">
          <input type="text" id="address" name="address" placeholder="Address" class="form-control" value="<%= @barbershop.address %>">
        </div>
      </div>

      <!-- Label and input for hood_id -->
      <div class="form-group">
        <label for="hood_id" class="col-sm-2 control-label">
          Hood
        </label>
        <div class="col-sm-10">
          <%= select_tag(:hood_id, options_from_collection_for_select(Hood.all, :id, :name), :class => "form-control" ) %>
        </div>
      </div>

      <!-- Label and input for telephone -->
      <div class="form-group">
        <label for="telephone" class="col-sm-2 control-label">
          Telephone
        </label>
        <div class="col-sm-10">
          <input type="text" id="telephone" name="telephone" placeholder="Telephone" class="form-control" value="<%= @barbershop.telephone %>">
        </div>
      </div>

   <!-- Label latitude not sure if i need it here-->



      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <input type="submit" value="Create Barbershop" class="btn btn-success">
          or
          <a href="/barbershops">Cancel</a>
        </div>
      </div>
    </form>
  </div>
</div>

<!-- End simple full-width example-->

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Barbershop</h3>
      </div>
      <div class="panel-body">
        <form action="/create_barbershop" class="form-horizontal">
          <!-- Label and input for name -->
          <div class="form-group">
            <label for="name" class="col-sm-2 control-label">
              Name
            </label>
            <div class="col-sm-10">
              <input type="text" id="name" name="name" placeholder="Name" class="form-control" value="<%= @barbershop.name %>">
            </div>
          </div>

          <!-- Label and input for address -->
          <div class="form-group">
            <label for="address" class="col-sm-2 control-label">
              Address
            </label>
            <div class="col-sm-10">
              <input type="text" id="address" name="address" placeholder="Address" class="form-control" value="<%= @barbershop.address %>">
            </div>
          </div>

          <!-- Label and input for hood_id -->
          <div class="form-group">
            <label for="hood_id" class="col-sm-2 control-label">
              Hood
            </label>
            <div class="col-sm-10">
              <input type="text" id="hood_id" name="hood_id" placeholder="Hood" class="form-control" value="<%= @barbershop.hood_id %>">
            </div>
          </div>

          <!-- Label and input for telephone -->
          <div class="form-group">
            <label for="telephone" class="col-sm-2 control-label">
              Telephone
            </label>
            <div class="col-sm-10">
              <input type="text" id="telephone" name="telephone" placeholder="Telephone" class="form-control" value="<%= @barbershop.telephone %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Create Barbershop" class="btn btn-success">
              or
              <a href="/barbershops">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->
</div>

app/views/barbershops/show.html.erb
<div class="content-container">
<!-- Simple full-width example-->

<div class="page-header">
  <!-- <h1>Barbershop #<%= @barbershop.name %></h1> -->
  <h1><%= @barbershop.name %></h1>
</div>

<div class = "one-half-left">

<dt>Map</dt>
      <dd>

        <!-- Code for Google Map -->
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
        <div id="map-canvas" style="height: 400px"></div>
        <script>

          function initialize() {

            var map;

            var myCenter = new google.maps.LatLng( <%= @barbershop.latitude %>, <%= @barbershop.longitude %>);

            var mapOptions = {
              zoom: 15,
              center: myCenter
            };

            map = new google.maps.Map(document.getElementById('map-canvas'),
              mapOptions);


            var myLatlng = new google.maps.LatLng(<%= @barbershop.latitude %>, <%= @barbershop.longitude %>);
            var marker = new google.maps.Marker({
              position: myLatlng,
              map: map,
              title: '<%= @barbershop.name %>'
            });
          }

          google.maps.event.addDomListener(window, 'load', initialize);

        </script>

      </dd>
</div>

<div class = "one-half-right">
<!-- <div class="row">
  <div class="col-md-12"> -->
    <dl class="dl-horizontal">
      <!-- <dt>Name</dt>
      <dd><%= @barbershop.name %></dd> -->
<div class=" details-container">

      <dt>Address</dt>
      <dd><%= @barbershop.address %></dd>

      <dt>Neighborhood</dt>
      <dd><%= @barbershop.hood.name %></dd>

      <dt>Telephone</dt>
      <dd><%= @barbershop.telephone %></dd>

      <dt></dt>
      <dd>
        <div class="btn-group">
          <a href="/barbershops" class="btn btn-primary">
            <i class="fa fa-chevron-left"></i>
          </a>
          <% if current_user.admin == true %>
          <a href="/barbershops/<%= @barbershop.id %>/edit" class="btn btn-warning">
            <i class="fa fa-edit"></i>
          </a>

          <a href="/delete_barbershop/<%= @barbershop.id %>" class="btn btn-danger">
            <i class="fa fa-trash-o"></i>
          </a>
          <% end %>
        </div>
      </dd>
    </dl>
</div>

 <!--  </div>
</div> -->

<!-- End simple full-width example-->


<!-- Loops through the barbers at this shop-->

<div class = "ratings-container">
        <% barber_ids = [] %>
        <% barber_ids = WorksAt.where(barbershop_id: @barbershop.id).pluck(:barber_id).uniq %>

        <% Barber.where(id: barber_ids ).each  do |barber| %>

        <div class="row">
        <hr>
          <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title"><%= barber.username  %></h3>
              </div>
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-12">
                    <dl class="dl-horizontal">


                     <div class="media">
                       <a class="media-left" href="/barbers/<%= barber.id %>">
                        <img src="<%= barber.avatar_url %>" alt="" class="img-circle" width="80">
                      </a>
                      <div class="media-body">
                        <h4 class="media-heading"><a href="/barbers/<%= barber.id %>">
                        <%= barber.username %></a></h4>
                        <dt>First Name</dt>
                        <dd><%= barber.first_name %></dd>
                        <dt>Average rating</dt>
          <% if barber.ratings.average(:rating).present? %>
          <dd><%= barber.ratings.average(:rating).round(1) %></dd>
          <% else %>
          <dd>No ratings yet</dd>
          <% end %>

                      </div>
                    </div>
                  </dl>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
    <% end %>

<!-- End responsive panel example -->
</div>
</div>